finished second parth
GregoryMaklakov/login pull request #1
Opened 2022-11-12 10:30 UTC by GregoryMaklakov

2022-11-14 11:45 UTC, a1exalexander requested changes
Усе тіп топ! Але потрібно зробити кілька правок

- [ ] Дороби класи блок/елемент (те, що я вказав в коментах)

- [ ] зроби висоту сторінки коджної мінімум `100vh`, бо так не дуже гарно
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/40409129/201651723-3e91f0e3-6c55-4d5e-ac4c-db915bf44688.png">

- [ ] баг з інпутом, якщо ввести неправильний імейл
<img width="400" alt="image" src="https://user-images.githubusercontent.com/40409129/201651933-6f67b67a-8db0-430b-8737-87b4105a040a.png">

2022-11-14 11:45 UTC, a1exalexander commented on style.css
> +}
👍

2022-11-14 11:45 UTC, a1exalexander commented on style.css
> +}
`input` завжди є також блоковим компонентом, тому всі стилі окрім відступів треба застосовувати до блока `.input {}`, або ж в твоєму випадку можна взагалі все що всерездині тега `label` зробити блоком `.input {}`

2022-11-15 10:34 UTC, GregoryMaklakov commented
Исправил второй и третий пункт!
Первый тоже постарался, но для меня легче все заново сделать чем переделывать :)

Тритий пункт - нашел решение в интернете:


14.11.2022, 12:45 +0100, Oleksandr Ratushnyi ***@***.***>, писал:
> @a1exalexander requested changes on this pull request.
> Усе тіп топ! Але потрібно зробити кілька правок
>
> • > Дороби класи блок/елемент (те, що я вказав в коментах)
> • > зроби висоту сторінки коджної мінімум 100vh, бо так не дуже гарно
>
>
> • баг з інпутом, якщо ввести неправильний імейл
>
> In style.css:
> > ***@***.*** gradient {
>
> +       0% {
>
> +               background-position: 12% 20%;
>
> +       }
>
> +       50% {
>
> +               background-position: 20% 30%;
>
> +       }
>
> +       100% {
>
> +               background-position: 12% 20%;
>
> +       }
>
> +}
>
> 👍
> In style.css:
> > +.form-advanced__input {
>
> +    width: 100%;
>
> +    border: 1px solid #3F3B4C;
>
> +    border-radius: 8px;
>
> +    background-color: inherit;
>
> +    padding: 11px 0px 11px 56px;
>
> +    transition: all 0.3s ease 0s;
>
> +
>
> +    font-weight: 600;
>
> +    font-size: 16px;
>
> +    line-height: 150%;
>
> +    color: #FFFFFF;
>
> +}
>
> +
>
> +.form-advanced__input:hover {
>
> +    background: #201C2D;
>
> +}
>
> +
>
> +.form-advanced__input:focus {
>
> +    box-shadow: 0px 0px 0px 1px #7B14FF;
>
> +    outline: none !important;
>
> +}
>
> +
>
> +.form-advanced__input:focus + .form-advanced__image .form-advanced__icon  {
>
> +  fill: #7B14FF;
>
> +}
>
> input завжди є також блоковим компонентом, тому всі стилі окрім відступів треба застосовувати до блока .input {}, або ж в твоєму випадку можна взагалі все що всерездині тега label зробити блоком .input {}
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-11-16 13:52 UTC, merged